version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: tbm_postgres
    restart: always
    volumes:
      - "tbm_postgresql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: tbm
      POSTGRES_USER: tbm
      POSTGRES_PASSWORD: tbm
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    container_name: tbm_redis
    ports:
      - "6379:6379"

volumes:
  tbm_postgresql_data:
