version: "3.8"

services:
  postgres:
    image: mariadb:10
    container_name: tvbb_mariadb
    restart: always
    volumes:
      - "tvbb_mariadb_data:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: tvbb
      MARIADB_USER: tvbb
      MARIADB_PASSWORD: tvbb
      MARIADB_ROOT_PASSWORD: tvbb
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    restart: always
    container_name: tvbb_redis
    ports:
      - "6379:6379"

volumes:
  tvbb_mariadb_data:
